[package]
name = "bokeh-models"
version = "0.1.0"
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]

[dependencies]
serde_json = "1.0.33"
serde = "1.0.80"
failure = "0.1.3"
askama = "0.7.2"
lazy_static = "1.2.0"

[dev-dependencies]
rand = "0.6.0"

[build-dependencies]
askama = "0.7.2"
